services:
  - type: web
    name: n8n-instagram-poster
    runtime: docker
    dockerfilePath: render/Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_ACCESS_TOKEN
        sync: false
      - key: FB_PAGE_ID
        sync: false
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: IG_USER_ID
        sync: false
      - key: IMGBB_API_KEY
        sync: false
